name = "rafter-materials-sync"
main = "index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "RAFTER_CLIENTS"
id = "7c7ad02d8136452eb6d03d1af89a684f"

[[r2_buckets]]
binding = "RAFTER_ASSETS"
bucket_name = "rafter-assets"

[[d1_databases]]
binding = "RAFTER_EVENTS"
database_name = "rafter-events"
database_id = "39f38376-d163-439b-984d-2f0889e88d56"

[[d1_databases]]
binding = "RAFTER_QUOTES"
database_name = "rafter-quotes"
database_id = "71594968-73c4-490a-b4bc-a425b0400402"

[triggers]
crons = ["0 10 * * *"]
